### ISSUE TITLE
Usage inside ionic 3

### ISSUE THREAD

**Issue by AbraamNader** [atwwei/ngx-dfp#2]
Hi,

The module works fine in the sample app, however if I use it inside an Ionic 3 app, I get this error on build:
`
[16:48:42]  ionic-app-script task: "build"
[16:48:42]  Error: ./node_modules/ngx-dfp/index.ts Module build fa
iled: Error: ENOENT: no such file or directory, open
            '...\node_modules\ngx-d
fp\index.js' at Error (native) @
            ./src/app/app.module.ts 13:0-36 @ ./src/app/main.ts
Error: ./node_modules/ngx-dfp/index.ts
Module build failed: Error: ENOENT: no such file or directory, ope
n 'D:\Documents\Projects\Cross\FilFan\node_modules\ngx-dfp\index.j
s'
    at Error (native)
 @ ./src/app/app.module.ts 13:0-36
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (...\node_mod
ules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (...\node_modules\@
ionic\app-scripts\dist\webpack.js:119:28)
    at emitRecords.err (...\node_mo
dules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (...\no
de_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (...\node_mod
ules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (...\node_modules\webpack\lib\Compiler.js:368:12)
    at next (...\node_modules\tapab
le\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (...\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (...\node_modules\tapable\lib\Tapable.js:222:13)
`
Dev Environment:
`
Ionic Framework: 3.6.1
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.9.2
OS Platform: Windows 10
`

Does this mean it needs the node module to be compiled to js along with map file?

Would appreciate any help.

Thanks.

**Comment by atwwei** [comment]
Yes, I think so.
And the package is compiled into js.
Now you can update the package and try again.

Thanks for your issue !

**Comment by atwwei** [comment]
Yes, I think so.
And the package is compiled into js.
Now you can update the package and try again.

Thanks for your issue !

**Comment by AbraamNader** [comment]
Thank you so much for your quick response, it is working perfectly.
Keep up the great work!
